// Generated by .tools/build_ym_films.py — do not edit by hand.
// Chapter timestamps match the rendered films in public/films/.
// Footage: Creative Commons Attribution (CC BY) via YouTube.

export interface FilmChapter { t: number; label: string }
export interface CircuitFilm {
  circuitId: string;
  src: string;
  poster: string;
  duration: number;
  chapters: FilmChapter[];
  credits: string[];
}

export const CIRCUIT_FILMS: Record<string, CircuitFilm> = {
  C1: { circuitId: 'C1', src: '/films/c1.mp4', poster: '/films/c1.jpg', duration: 29.9, chapters: [{ t: 2.4, label: 'Bahu Fort' }, { t: 7.7, label: 'Bahu–Mahamaya Ropeway' }, { t: 14.0, label: 'The Tawi below' }, { t: 19.3, label: 'Bagh-e-Bahu' }, { t: 24.6, label: 'Tawi Aarti' }], credits: ['Bahu Fort viewpoint — ALL VIDEOS', 'Jammu ropeway trial — Jkupdate', 'Tawi aerial — STrange WoRlD', 'Bagh-e-Bahu gardens — Viral video official', 'Floating diyas — eyesup', 'Music — “Kun Faya Kun” · Rockstar (A.R. Rahman)'] },
  C2: { circuitId: 'C2', src: '/films/c2.mp4', poster: '/films/c2.jpg', duration: 28.9, chapters: [{ t: 2.4, label: 'Mubarak Mandi' }, { t: 6.7, label: 'Raghunath Temple' }, { t: 12.0, label: 'Raghunath Bazaar' }, { t: 18.3, label: 'Ranbireshwar Temple' }, { t: 23.6, label: 'Diyas at dusk' }], credits: ['Mubarak Mandi — Peepul Tree World', 'Raghunath Temple — Tilak', 'Raghunath Bazaar walkthrough — Mute Maps', 'Ranbireshwar Temple — WildFilmsIndia', 'Floating diyas — eyesup', 'Music — “Kun Faya Kun” · Rockstar (A.R. Rahman)'] },
  C6: { circuitId: 'C6', src: '/films/c6.mp4', poster: '/films/c6.jpg', duration: 30.9, chapters: [{ t: 2.4, label: 'The riverfront' }, { t: 7.7, label: 'Bridges over the Tawi' }, { t: 13.0, label: 'The city across the river' }, { t: 18.3, label: 'Light and sound show' }, { t: 25.6, label: 'Tawi Aarti' }], credits: ['Tawi riverfront — STrange WoRlD', 'Tawi bridges — STrange WoRlD', 'Across the Tawi — ALL VIDEOS', 'Bagh-e-Bahu light & sound — Lets See God', 'Floating diyas — eyesup', 'Music — “Kun Faya Kun” · Rockstar (A.R. Rahman)'] },
};
